#!/usr/bin/env bash
# Copyright Siemens AG, 2015. Part of the SW360 Portal Project.
#
# SPDX-License-Identifier: EPL-1.0
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

. ./utilsSW360
. ./folderManager

groupname=
uploadId=
while getopts g:u: opt; do
  case ${opt} in
    u) uploadId="$OPTARG";;
    g) groupname="$OPTARG";;
  esac
done

checkNotEmpty "$groupname" "$uploadId" || die 1 "bad options $@"

checkNotEmpty "$FOSSUSER" "$FOSSPASS" || die 2 "no user or password known for group='$groupname'"

foMakeAdmin=$( runWithUserAndPass fo_chmod --uploadId "$uploadId" --destgroup "$groupname" )

(($?!=0)) && die 3 "fossupload_status failed:" "$foMakeAdmin"

targetFolderId=$( getFolderId "$groupname" )

(($?==0)) && checkNotEmpty "$targetFolderId" || die 4 "destination folder for $groupname not found"

linkUploadInFolder "$uploadId" "$targetFolderId"

# TODO optionally schedule reuser to make decisions available to the new group, or implement a dedicated UI
