#!/usr/bin/env bash
# Copyright Siemens AG, 2015. Part of the SW360 Portal Project.
#
# SPDX-License-Identifier: EPL-1.0
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

. ./utilsSW360

getFolderId() {
  local groupname="$1"
  checkNotEmpty "$groupname" || die 1 "cannot get inbox folder of empty team"

  local folderStructure="$( runWithUserAndPass fo_folder )"

  (($?==0)) || checkNotEmpty "$folderStructure" || die 2 "cannot retrieve folder structure"

  log "debug" "current folder structure: $folderStructure"

  local folderId=""
  while read line; do
    if [[ "$line" =~ -*$groupname\ *\(id=([0-9]+)\) ]]; then
      folderId="${BASH_REMATCH[1]}"
      break
    fi
  done <<<"$folderStructure"

  log "debug" "got $folderId for $groupname"

  checkNotEmpty "$folderId" || die 3 "folder of group $groupname not found"
  echo "$folderId"
}

linkUploadInFolder() {
  local uploadId="$1"
  local destFolderId="$2"

  checkNotEmpty "$uploadId" "$destFolderId" || die 1 "bad parameters"

  runWithUserAndPass fo_folder --linkUpload "$uploadId" --folderId "$destFolderId"
}