#!/usr/bin/env bash
# Copyright Siemens AG, 2015. Part of the SW360 Portal Project.
#
# SPDX-License-Identifier: EPL-1.0
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

FOSSUSER=sw360
FOSSPASS=sw360

# name of the FOSSology group
FOSSY_GROUP=fossy

logDir="$HOME/log"

ensureDir() {
  [[ ! -d "$1" ]] && mkdir -p "$1"
  [[ ! -d "$1" ]] && die 2 "directory '$1' does not exist"
}

die() {
  local retCode=$1 msg
  shift
  for msg in "$@"; do
    echo "$msg"
  done
  log "dying with $retCode" "$@"
  exit ${retCode}
}

checkNotEmpty() {
  local arg
  for arg in "$@"; do
    [[ -z "$arg" ]] && return 1
  done
  return 0
}

checkNotEmpty "$FOSSUSER" "$FOSSPASS" "$FOSSY_GROUP" || die 3 "no user or password known"

runWithUserAndPass() {
   log "running" "$@"

   local out="$( "$@" --username "$FOSSUSER" <<<"$FOSSPASS" 2>&1 )"
   local rt=$?

   log "output" "$out"

   echo "$out"
   return ${rt}
}

ensureDir "$logDir"
logFile="$logDir/$(date +%Y%m%d.%H-%M-%S)"
log() {
  echo "$@" >> "$logFile"
}