# SPDX-FileCopyrightText: © 2025 Siemens AG

# SPDX-License-Identifier: EPL-2.0
image: debian:bullseye

stages:
  - build
  - container-image

include:
  - project: awesome-ci/templates
    ref: v2.4.0 # Insert desired version from https://code.siemens.com/awesome-ci/templates/-/releases
    file:
      - docker/build-docker-image.gitlab-ci.yml

services:
  - couchdb:3.4

variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  HTTP_PROXY: $CODE_PROXY
  HTTPS_PROXY: $CODE_PROXY
  no_proxy: "${CODE_NO_PROXY},.siemens.net,.siemens.com,.siemens.co.in,couchdb"
  COUCHDB_USER: $COUCHDB_TEST_USER
  COUCHDB_PASSWORD: $COUCHDB_TEST_PWD
  BUILD_ARTIFACT_ROOT: $CI_PROJECT_DIR/artifacts
  _JAVA_OPTIONS: -Djdk.net.URLClassPath.disableClassPathURLCheck=true -DSPDXParser.OnlyUseLocalLicenses=true -Dhttp.proxySet=true -Dhttp.proxyHost=$CODE_PROXY_HOST -Dhttp.proxyPort=$CODE_PROXY_PORT -Dhttp.nonProxyHosts=localhost|couchdb
  GRADLE_USER_HOME: $HOME/.gradle
  # Use m2 repository in build dir for caching
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Xmx3072m"
  KC_VERSION: 26.2.0

################
# Helper anchors
################
.package_proxy: &setup_proxies
  - |
    mkdir -p /etc/apt/apt.conf.d
    printf "Acquire::http::proxy \"%s\";\nAcquire::https::proxy \"%s\";\n" \
      "${http_proxy}" "${https_proxy}" > /etc/apt/apt.conf.d/95proxy

  # setting remote repos url to download mvn packages
  - printf '<settings><mirrors><mirror><mirrorOf>*</mirrorOf><name>remote-repos</name><url>https://devops.bt.siemens.com/artifactory/maven2-all</url><id>remote-repos</id></mirror></mirrors></settings>' > ~/.m2/settings.xml

  # setting proxy for gradle, required to build thrift
  - |
    mkdir -p $GRADLE_USER_HOME
    printf "systemProp.http.proxyHost=%s
    systemProp.http.proxyPort=%s
    systemProp.http.nonProxyHosts='%s'
    systemProp.https.proxyHost=%s
    systemProp.https.proxyPort=%s
    " \
      "$CODE_PROXY_HOST" "$CODE_PROXY_PORT" "localhost|couchdb|*.siemens.com|*.siemens.de|*.siemens.co.in" \
      "$CODE_PROXY_HOST" "$CODE_PROXY_PORT" >> $GRADLE_USER_HOME/gradle.properties

.install_thrift: &install_thrift
  - apt-get update -qq
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq build-essential libevent-dev libtool flex bison pkg-config libssl-dev git cmake
  - chmod +x third-party/thrift/install-thrift.sh
  - DESTDIR=$CI_PROJECT_DIR/dist/thrift-$THRIFT_VERSION third-party/thrift/install-thrift.sh

build:
  stage: build
  image: maven:3-eclipse-temurin-21
  before_script:
    - mkdir -p ${BUILD_ARTIFACT_ROOT}/tomcat ${BUILD_ARTIFACT_ROOT}/keycloak /etc/sw360/ $CI_PROJECT_DIR/.m2/repository

    - *setup_proxies

    - cp ./build-configuration/test-resources/couchdb-test.properties /etc/sw360/
    - sed -i 's/^\(couchdb.url\s*=\).*/\1 http:\/\/couchdb:5984/' /etc/sw360/couchdb-test.properties
    - sed -i 's/^\(couchdb.user\s*=\).*/\1 '${COUCHDB_TEST_USER}'/' /etc/sw360/couchdb-test.properties
    - sed -i 's/^\(couchdb.password\s*=\).*/\1 '${COUCHDB_TEST_PWD}'/' /etc/sw360/couchdb-test.properties

    - *install_thrift

    # Check if CouchDB is running
    - curl -s couchdb:5984/_up | grep -q '"status":"ok"'

    # Checkout branch for proper footer
    - git checkout ${CI_COMMIT_REF_NAME}

  script:
    # Build code and create artifacts
    - |
      export PATH=$PATH:$CI_PROJECT_DIR/dist/thrift-$THRIFT_VERSION/usr/local/bin
      mvn clean install \
        --no-transfer-progress \
        -P deploy -Dhelp-docs=true \
        -Dbase.deploy.dir=${BUILD_ARTIFACT_ROOT}/tomcat \
        -Dlistener.deploy.dir=${BUILD_ARTIFACT_ROOT}/keycloak \
        -DRunComponentVisibilityRestrictionTest=false \
        -DRunPrivateProjectAccessTest=false \
        -DRunRestForceUpdateTest=false \
        -fae \
        -Dmaven.plugin.validation=VERBOSE
  cache:
    - key: maven
      paths:
        - $CI_PROJECT_DIR/.m2/repository
    - key: thrift-$THRIFT_VERSION
      paths:
        - $CI_PROJECT_DIR/dist/thrift-$THRIFT_VERSION
  artifacts:
    when: always
    reports:
      junit:
        - ./**/target/surefire-reports/TEST-*.xml
        - ./**/target/failsafe-reports/TEST-*.xml
    paths:
      - $BUILD_ARTIFACT_ROOT

Docker-latest:
  extends: .awesome-ci/build-docker-image
  stage: container-image
  rules:
    - if: $CI_COMMIT_BRANCH == "mainct"
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/keycloak
    EXTRA_ARGUMENTS: --build-arg KC_VERSION=$KC_VERSION
    IMAGE_TAG: $KC_VERSION
    DOCKERFILE: $CI_PROJECT_DIR/Dockerfile.keycloak
  needs:
    - job: build
      artifacts: true
