/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "t_test_empty_service.h"

GType
t_test_empty_service_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (TTestEmptyServiceIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "TTestEmptyServiceIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
t_test_empty_service_if_interface_init (TTestEmptyServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (TTestEmptyServiceClient, t_test_empty_service_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (T_TEST_TYPE_EMPTY_SERVICE_IF,
                                                t_test_empty_service_if_interface_init))

enum _TTestEmptyServiceClientProperties
{
  PROP_0,
  PROP_T_TEST_EMPTY_SERVICE_CLIENT_INPUT_PROTOCOL,
  PROP_T_TEST_EMPTY_SERVICE_CLIENT_OUTPUT_PROTOCOL
};

void
t_test_empty_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  TTestEmptyServiceClient *client = T_TEST_EMPTY_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_T_TEST_EMPTY_SERVICE_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_T_TEST_EMPTY_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
t_test_empty_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  TTestEmptyServiceClient *client = T_TEST_EMPTY_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_T_TEST_EMPTY_SERVICE_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_T_TEST_EMPTY_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

static void
t_test_empty_service_if_interface_init (TTestEmptyServiceIfInterface *iface)
{
  THRIFT_UNUSED_VAR (iface);
}

static void
t_test_empty_service_client_init (TTestEmptyServiceClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
t_test_empty_service_client_class_init (TTestEmptyServiceClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = t_test_empty_service_client_set_property;
  gobject_class->get_property = t_test_empty_service_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_T_TEST_EMPTY_SERVICE_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_T_TEST_EMPTY_SERVICE_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
t_test_empty_service_handler_empty_service_if_interface_init (TTestEmptyServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (TTestEmptyServiceHandler, 
                         t_test_empty_service_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (T_TEST_TYPE_EMPTY_SERVICE_IF,
                                                t_test_empty_service_handler_empty_service_if_interface_init))

static void
t_test_empty_service_handler_empty_service_if_interface_init (TTestEmptyServiceIfInterface *iface)
{
THRIFT_UNUSED_VAR (iface);
}

static void
t_test_empty_service_handler_init (TTestEmptyServiceHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
t_test_empty_service_handler_class_init (TTestEmptyServiceHandlerClass *cls)
{
  THRIFT_UNUSED_VAR (cls);
}

enum _TTestEmptyServiceProcessorProperties
{
  PROP_T_TEST_EMPTY_SERVICE_PROCESSOR_0,
  PROP_T_TEST_EMPTY_SERVICE_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (TTestEmptyServiceProcessor,
               t_test_empty_service_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* TTestEmptyServiceProcessorProcessFunction) (TTestEmptyServiceProcessor *, 
                                                                gint32,
                                                                ThriftProtocol *,
                                                                ThriftProtocol *,
                                                                GError **);

typedef struct
{
  gchar *name;
  TTestEmptyServiceProcessorProcessFunction function;
} t_test_empty_service_processor_process_function_def;


static gboolean
t_test_empty_service_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                              ThriftProtocol *input_protocol,
                                              ThriftProtocol *output_protocol,
                                              gchar *method_name,
                                              gint32 sequence_id,
                                              GError **error)
{
  t_test_empty_service_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  TTestEmptyServiceProcessor *self = T_TEST_EMPTY_SERVICE_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (T_TEST_EMPTY_SERVICE_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
t_test_empty_service_processor_set_property (GObject *object,
                                             guint property_id,
                                             const GValue *value,
                                             GParamSpec *pspec)
{
  TTestEmptyServiceProcessor *self = T_TEST_EMPTY_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_T_TEST_EMPTY_SERVICE_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
t_test_empty_service_processor_get_property (GObject *object,
                                             guint property_id,
                                             GValue *value,
                                             GParamSpec *pspec)
{
  TTestEmptyServiceProcessor *self = T_TEST_EMPTY_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_T_TEST_EMPTY_SERVICE_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
t_test_empty_service_processor_dispose (GObject *gobject)
{
  TTestEmptyServiceProcessor *self = T_TEST_EMPTY_SERVICE_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (t_test_empty_service_processor_parent_class)->dispose (gobject);
}

static void
t_test_empty_service_processor_finalize (GObject *gobject)
{
  TTestEmptyServiceProcessor *self = T_TEST_EMPTY_SERVICE_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (t_test_empty_service_processor_parent_class)->finalize (gobject);
}

static void
t_test_empty_service_processor_init (TTestEmptyServiceProcessor *self)
{
  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);
}

static void
t_test_empty_service_processor_class_init (TTestEmptyServiceProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = t_test_empty_service_processor_dispose;
  gobject_class->finalize = t_test_empty_service_processor_finalize;
  gobject_class->set_property = t_test_empty_service_processor_set_property;
  gobject_class->get_property = t_test_empty_service_processor_get_property;

  dispatch_processor_class->dispatch_call = t_test_empty_service_processor_dispatch_call;
  cls->dispatch_call = t_test_empty_service_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    T_TEST_TYPE_EMPTY_SERVICE_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_T_TEST_EMPTY_SERVICE_PROCESSOR_HANDLER,
                                   param_spec);
}
