/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef T_TEST_EMPTY_SERVICE_H
#define T_TEST_EMPTY_SERVICE_H

#include <thrift/c_glib/processor/thrift_dispatch_processor.h>

#include "t_test_debug_proto_test_types.h"

/* EmptyService service interface */
typedef struct _TTestEmptyServiceIf TTestEmptyServiceIf;  /* dummy object */

struct _TTestEmptyServiceIfInterface
{
  GTypeInterface parent;

};
typedef struct _TTestEmptyServiceIfInterface TTestEmptyServiceIfInterface;

GType t_test_empty_service_if_get_type (void);
#define T_TEST_TYPE_EMPTY_SERVICE_IF (t_test_empty_service_if_get_type())
#define T_TEST_EMPTY_SERVICE_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_EMPTY_SERVICE_IF, TTestEmptyServiceIf))
#define T_TEST_IS_EMPTY_SERVICE_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_EMPTY_SERVICE_IF))
#define T_TEST_EMPTY_SERVICE_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), T_TEST_TYPE_EMPTY_SERVICE_IF, TTestEmptyServiceIfInterface))


/* EmptyService service client */
struct _TTestEmptyServiceClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _TTestEmptyServiceClient TTestEmptyServiceClient;

struct _TTestEmptyServiceClientClass
{
  GObjectClass parent;
};
typedef struct _TTestEmptyServiceClientClass TTestEmptyServiceClientClass;

GType t_test_empty_service_client_get_type (void);
#define T_TEST_TYPE_EMPTY_SERVICE_CLIENT (t_test_empty_service_client_get_type())
#define T_TEST_EMPTY_SERVICE_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_EMPTY_SERVICE_CLIENT, TTestEmptyServiceClient))
#define T_TEST_EMPTY_SERVICE_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), T_TEST_TYPE_EMPTY_SERVICE_CLIENT, TTestEmptyServiceClientClass))
#define T_TEST_EMPTY_SERVICE_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_EMPTY_SERVICE_CLIENT))
#define T_TEST_EMPTY_SERVICE_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), T_TEST_TYPE_EMPTY_SERVICE_CLIENT))
#define T_TEST_EMPTY_SERVICE_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TEST_TYPE_EMPTY_SERVICE_CLIENT, TTestEmptyServiceClientClass))

void empty_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
void empty_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);

/* EmptyService handler (abstract base class) */
struct _TTestEmptyServiceHandler
{
  GObject parent;
};
typedef struct _TTestEmptyServiceHandler TTestEmptyServiceHandler;

struct _TTestEmptyServiceHandlerClass
{
  GObjectClass parent;

};
typedef struct _TTestEmptyServiceHandlerClass TTestEmptyServiceHandlerClass;

GType t_test_empty_service_handler_get_type (void);
#define T_TEST_TYPE_EMPTY_SERVICE_HANDLER (t_test_empty_service_handler_get_type())
#define T_TEST_EMPTY_SERVICE_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_EMPTY_SERVICE_HANDLER, TTestEmptyServiceHandler))
#define T_TEST_IS_EMPTY_SERVICE_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_EMPTY_SERVICE_HANDLER))
#define T_TEST_EMPTY_SERVICE_HANDLER_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), T_TEST_TYPE_EMPTY_SERVICE_HANDLER, TTestEmptyServiceHandlerClass))
#define T_TEST_IS_EMPTY_SERVICE_HANDLER_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), T_TEST_TYPE_EMPTY_SERVICE_HANDLER))
#define T_TEST_EMPTY_SERVICE_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TEST_TYPE_EMPTY_SERVICE_HANDLER, TTestEmptyServiceHandlerClass))


/* EmptyService processor */
struct _TTestEmptyServiceProcessor
{
  ThriftDispatchProcessor parent;

  /* protected */
  TTestEmptyServiceHandler *handler;
  GHashTable *process_map;
};
typedef struct _TTestEmptyServiceProcessor TTestEmptyServiceProcessor;

struct _TTestEmptyServiceProcessorClass
{
  ThriftDispatchProcessorClass parent;

  /* protected */
  gboolean (*dispatch_call) (ThriftDispatchProcessor *processor,
                             ThriftProtocol *in,
                             ThriftProtocol *out,
                             gchar *fname,
                             gint32 seqid,
                             GError **error);
};
typedef struct _TTestEmptyServiceProcessorClass TTestEmptyServiceProcessorClass;

GType t_test_empty_service_processor_get_type (void);
#define T_TEST_TYPE_EMPTY_SERVICE_PROCESSOR (t_test_empty_service_processor_get_type())
#define T_TEST_EMPTY_SERVICE_PROCESSOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TEST_TYPE_EMPTY_SERVICE_PROCESSOR, TTestEmptyServiceProcessor))
#define T_TEST_IS_EMPTY_SERVICE_PROCESSOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TEST_TYPE_EMPTY_SERVICE_PROCESSOR))
#define T_TEST_EMPTY_SERVICE_PROCESSOR_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), T_TEST_TYPE_EMPTY_SERVICE_PROCESSOR, TTestEmptyServiceProcessorClass))
#define T_TEST_IS_EMPTY_SERVICE_PROCESSOR_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), T_TEST_TYPE_EMPTY_SERVICE_PROCESSOR))
#define T_TEST_EMPTY_SERVICE_PROCESSOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TEST_TYPE_EMPTY_SERVICE_PROCESSOR, TTestEmptyServiceProcessorClass))

#endif /* T_TEST_EMPTY_SERVICE_H */
