/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "t_test_srv.h"

gboolean
t_test_srv_if_janky (TTestSrvIf *iface, gint32* _return, const gint32 arg, GError **error)
{
  return T_TEST_SRV_IF_GET_INTERFACE (iface)->janky (iface, _return, arg, error);
}

gboolean
t_test_srv_if_void_method (TTestSrvIf *iface, GError **error)
{
  return T_TEST_SRV_IF_GET_INTERFACE (iface)->void_method (iface, error);
}

gboolean
t_test_srv_if_primitive_method (TTestSrvIf *iface, gint32* _return, GError **error)
{
  return T_TEST_SRV_IF_GET_INTERFACE (iface)->primitive_method (iface, _return, error);
}

gboolean
t_test_srv_if_struct_method (TTestSrvIf *iface, TTestCompactProtoTestStruct ** _return, GError **error)
{
  return T_TEST_SRV_IF_GET_INTERFACE (iface)->struct_method (iface, _return, error);
}

gboolean
t_test_srv_if_method_with_default_args (TTestSrvIf *iface, const gint32 something, GError **error)
{
  return T_TEST_SRV_IF_GET_INTERFACE (iface)->method_with_default_args (iface, something, error);
}

gboolean
t_test_srv_if_oneway_method (TTestSrvIf *iface, GError **error)
{
  return T_TEST_SRV_IF_GET_INTERFACE (iface)->oneway_method (iface, error);
}

gboolean
t_test_srv_if_declared_exception_method (TTestSrvIf *iface, gboolean* _return, const gboolean shouldThrow, TTestExceptionWithAMap ** xwamap, GError **error)
{
  return T_TEST_SRV_IF_GET_INTERFACE (iface)->declared_exception_method (iface, _return, shouldThrow, xwamap, error);
}

GType
t_test_srv_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (TTestSrvIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "TTestSrvIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
t_test_srv_if_interface_init (TTestSrvIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (TTestSrvClient, t_test_srv_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (T_TEST_TYPE_SRV_IF,
                                                t_test_srv_if_interface_init))

enum _TTestSrvClientProperties
{
  PROP_0,
  PROP_T_TEST_SRV_CLIENT_INPUT_PROTOCOL,
  PROP_T_TEST_SRV_CLIENT_OUTPUT_PROTOCOL
};

void
t_test_srv_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  TTestSrvClient *client = T_TEST_SRV_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_T_TEST_SRV_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_T_TEST_SRV_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
t_test_srv_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  TTestSrvClient *client = T_TEST_SRV_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_T_TEST_SRV_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_T_TEST_SRV_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean t_test_srv_client_send_janky (TTestSrvIf * iface, const gint32 arg, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "Janky", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "Janky_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "arg", T_I32, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, arg, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_recv_janky (TTestSrvIf * iface, gint32* _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "Janky", 5) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected Janky", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_I32)
          {
            if ((ret = thrift_protocol_read_i32 (protocol, &*_return, error)) < 0)
              return 0;
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_janky (TTestSrvIf * iface, gint32* _return, const gint32 arg, GError ** error)
{
  if (!t_test_srv_client_send_janky (iface, arg, error))
    return FALSE;
  if (!t_test_srv_client_recv_janky (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean t_test_srv_client_send_void_method (TTestSrvIf * iface, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "voidMethod", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "voidMethod_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_recv_void_method (TTestSrvIf * iface, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "voidMethod", 10) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected voidMethod", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_void_method (TTestSrvIf * iface, GError ** error)
{
  if (!t_test_srv_client_send_void_method (iface, error))
    return FALSE;
  if (!t_test_srv_client_recv_void_method (iface, error))
    return FALSE;
  return TRUE;
}

gboolean t_test_srv_client_send_primitive_method (TTestSrvIf * iface, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "primitiveMethod", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "primitiveMethod_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_recv_primitive_method (TTestSrvIf * iface, gint32* _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "primitiveMethod", 15) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected primitiveMethod", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_I32)
          {
            if ((ret = thrift_protocol_read_i32 (protocol, &*_return, error)) < 0)
              return 0;
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_primitive_method (TTestSrvIf * iface, gint32* _return, GError ** error)
{
  if (!t_test_srv_client_send_primitive_method (iface, error))
    return FALSE;
  if (!t_test_srv_client_recv_primitive_method (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean t_test_srv_client_send_struct_method (TTestSrvIf * iface, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "structMethod", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "structMethod_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_recv_struct_method (TTestSrvIf * iface, TTestCompactProtoTestStruct ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "structMethod", 12) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected structMethod", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_struct_method (TTestSrvIf * iface, TTestCompactProtoTestStruct ** _return, GError ** error)
{
  if (!t_test_srv_client_send_struct_method (iface, error))
    return FALSE;
  if (!t_test_srv_client_recv_struct_method (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean t_test_srv_client_send_method_with_default_args (TTestSrvIf * iface, const gint32 something, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "methodWithDefaultArgs", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "methodWithDefaultArgs_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "something", T_I32, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, something, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_recv_method_with_default_args (TTestSrvIf * iface, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "methodWithDefaultArgs", 21) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected methodWithDefaultArgs", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_method_with_default_args (TTestSrvIf * iface, const gint32 something, GError ** error)
{
  if (!t_test_srv_client_send_method_with_default_args (iface, something, error))
    return FALSE;
  if (!t_test_srv_client_recv_method_with_default_args (iface, error))
    return FALSE;
  return TRUE;
}

gboolean t_test_srv_client_send_oneway_method (TTestSrvIf * iface, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "onewayMethod", T_ONEWAY, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "onewayMethod_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_oneway_method (TTestSrvIf * iface, GError ** error)
{
  if (!t_test_srv_client_send_oneway_method (iface, error))
    return FALSE;
  return TRUE;
}

gboolean t_test_srv_client_send_declared_exception_method (TTestSrvIf * iface, const gboolean shouldThrow, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "declaredExceptionMethod", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "declaredExceptionMethod_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "shouldThrow", T_BOOL, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_bool (protocol, shouldThrow, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean t_test_srv_client_recv_declared_exception_method (TTestSrvIf * iface, gboolean* _return, TTestExceptionWithAMap ** xwamap, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = T_TEST_SRV_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "declaredExceptionMethod", 23) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected declaredExceptionMethod", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_BOOL)
          {
            if ((ret = thrift_protocol_read_bool (protocol, &*_return, error)) < 0)
              return 0;
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *xwamap != NULL)
            {
              g_object_unref (*xwamap);
            }
            *xwamap = g_object_new (T_TEST_TYPE_EXCEPTION_WITH_A_MAP, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*xwamap), protocol, error)) < 0)
            {
              g_object_unref (*xwamap);
              *xwamap = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*xwamap != NULL)
  {
      g_set_error (error, T_TEST_EXCEPTION_WITH_A_MAP_ERROR, T_TEST_EXCEPTION_WITH_A_MAP_ERROR_CODE, "ExceptionWithAMap");
      return FALSE;
  }
  return TRUE;
}

gboolean t_test_srv_client_declared_exception_method (TTestSrvIf * iface, gboolean* _return, const gboolean shouldThrow, TTestExceptionWithAMap ** xwamap, GError ** error)
{
  if (!t_test_srv_client_send_declared_exception_method (iface, shouldThrow, error))
    return FALSE;
  if (!t_test_srv_client_recv_declared_exception_method (iface, _return, xwamap, error))
    return FALSE;
  return TRUE;
}

static void
t_test_srv_if_interface_init (TTestSrvIfInterface *iface)
{
  iface->janky = t_test_srv_client_janky;
  iface->void_method = t_test_srv_client_void_method;
  iface->primitive_method = t_test_srv_client_primitive_method;
  iface->struct_method = t_test_srv_client_struct_method;
  iface->method_with_default_args = t_test_srv_client_method_with_default_args;
  iface->oneway_method = t_test_srv_client_oneway_method;
  iface->declared_exception_method = t_test_srv_client_declared_exception_method;
}

static void
t_test_srv_client_init (TTestSrvClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
t_test_srv_client_class_init (TTestSrvClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = t_test_srv_client_set_property;
  gobject_class->get_property = t_test_srv_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_T_TEST_SRV_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_T_TEST_SRV_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
t_test_srv_handler_srv_if_interface_init (TTestSrvIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (TTestSrvHandler, 
                         t_test_srv_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (T_TEST_TYPE_SRV_IF,
                                                t_test_srv_handler_srv_if_interface_init))

gboolean t_test_srv_handler_janky (TTestSrvIf * iface, gint32* _return, const gint32 arg, GError ** error)
{
  g_return_val_if_fail (T_TEST_IS_SRV_HANDLER (iface), FALSE);

  return T_TEST_SRV_HANDLER_GET_CLASS (iface)->janky (iface, _return, arg, error);
}

gboolean t_test_srv_handler_void_method (TTestSrvIf * iface, GError ** error)
{
  g_return_val_if_fail (T_TEST_IS_SRV_HANDLER (iface), FALSE);

  return T_TEST_SRV_HANDLER_GET_CLASS (iface)->void_method (iface, error);
}

gboolean t_test_srv_handler_primitive_method (TTestSrvIf * iface, gint32* _return, GError ** error)
{
  g_return_val_if_fail (T_TEST_IS_SRV_HANDLER (iface), FALSE);

  return T_TEST_SRV_HANDLER_GET_CLASS (iface)->primitive_method (iface, _return, error);
}

gboolean t_test_srv_handler_struct_method (TTestSrvIf * iface, TTestCompactProtoTestStruct ** _return, GError ** error)
{
  g_return_val_if_fail (T_TEST_IS_SRV_HANDLER (iface), FALSE);

  return T_TEST_SRV_HANDLER_GET_CLASS (iface)->struct_method (iface, _return, error);
}

gboolean t_test_srv_handler_method_with_default_args (TTestSrvIf * iface, const gint32 something, GError ** error)
{
  g_return_val_if_fail (T_TEST_IS_SRV_HANDLER (iface), FALSE);

  return T_TEST_SRV_HANDLER_GET_CLASS (iface)->method_with_default_args (iface, something, error);
}

gboolean t_test_srv_handler_oneway_method (TTestSrvIf * iface, GError ** error)
{
  g_return_val_if_fail (T_TEST_IS_SRV_HANDLER (iface), FALSE);

  return T_TEST_SRV_HANDLER_GET_CLASS (iface)->oneway_method (iface, error);
}

gboolean t_test_srv_handler_declared_exception_method (TTestSrvIf * iface, gboolean* _return, const gboolean shouldThrow, TTestExceptionWithAMap ** xwamap, GError ** error)
{
  g_return_val_if_fail (T_TEST_IS_SRV_HANDLER (iface), FALSE);

  return T_TEST_SRV_HANDLER_GET_CLASS (iface)->declared_exception_method (iface, _return, shouldThrow, xwamap, error);
}

static void
t_test_srv_handler_srv_if_interface_init (TTestSrvIfInterface *iface)
{
  iface->janky = t_test_srv_handler_janky;
  iface->void_method = t_test_srv_handler_void_method;
  iface->primitive_method = t_test_srv_handler_primitive_method;
  iface->struct_method = t_test_srv_handler_struct_method;
  iface->method_with_default_args = t_test_srv_handler_method_with_default_args;
  iface->oneway_method = t_test_srv_handler_oneway_method;
  iface->declared_exception_method = t_test_srv_handler_declared_exception_method;
}

static void
t_test_srv_handler_init (TTestSrvHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
t_test_srv_handler_class_init (TTestSrvHandlerClass *cls)
{
  cls->janky = NULL;
  cls->void_method = NULL;
  cls->primitive_method = NULL;
  cls->struct_method = NULL;
  cls->method_with_default_args = NULL;
  cls->oneway_method = NULL;
  cls->declared_exception_method = NULL;
}

enum _TTestSrvProcessorProperties
{
  PROP_T_TEST_SRV_PROCESSOR_0,
  PROP_T_TEST_SRV_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (TTestSrvProcessor,
               t_test_srv_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* TTestSrvProcessorProcessFunction) (TTestSrvProcessor *, 
                                                       gint32,
                                                       ThriftProtocol *,
                                                       ThriftProtocol *,
                                                       GError **);

typedef struct
{
  gchar *name;
  TTestSrvProcessorProcessFunction function;
} t_test_srv_processor_process_function_def;

static gboolean
t_test_srv_processor_process_janky (TTestSrvProcessor *,
                                    gint32,
                                    ThriftProtocol *,
                                    ThriftProtocol *,
                                    GError **);
static gboolean
t_test_srv_processor_process_void_method (TTestSrvProcessor *,
                                          gint32,
                                          ThriftProtocol *,
                                          ThriftProtocol *,
                                          GError **);
static gboolean
t_test_srv_processor_process_primitive_method (TTestSrvProcessor *,
                                               gint32,
                                               ThriftProtocol *,
                                               ThriftProtocol *,
                                               GError **);
static gboolean
t_test_srv_processor_process_struct_method (TTestSrvProcessor *,
                                            gint32,
                                            ThriftProtocol *,
                                            ThriftProtocol *,
                                            GError **);
static gboolean
t_test_srv_processor_process_method_with_default_args (TTestSrvProcessor *,
                                                       gint32,
                                                       ThriftProtocol *,
                                                       ThriftProtocol *,
                                                       GError **);
static gboolean
t_test_srv_processor_process_oneway_method (TTestSrvProcessor *,
                                            gint32,
                                            ThriftProtocol *,
                                            ThriftProtocol *,
                                            GError **);
static gboolean
t_test_srv_processor_process_declared_exception_method (TTestSrvProcessor *,
                                                        gint32,
                                                        ThriftProtocol *,
                                                        ThriftProtocol *,
                                                        GError **);

static t_test_srv_processor_process_function_def
t_test_srv_processor_process_function_defs[7] = {
  {
    "Janky",
    t_test_srv_processor_process_janky
  },
  {
    "voidMethod",
    t_test_srv_processor_process_void_method
  },
  {
    "primitiveMethod",
    t_test_srv_processor_process_primitive_method
  },
  {
    "structMethod",
    t_test_srv_processor_process_struct_method
  },
  {
    "methodWithDefaultArgs",
    t_test_srv_processor_process_method_with_default_args
  },
  {
    "onewayMethod",
    t_test_srv_processor_process_oneway_method
  },
  {
    "declaredExceptionMethod",
    t_test_srv_processor_process_declared_exception_method
  }
};

static gboolean
t_test_srv_processor_process_janky (TTestSrvProcessor *self,
                                    gint32 sequence_id,
                                    ThriftProtocol *input_protocol,
                                    ThriftProtocol *output_protocol,
                                    GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  TTestSrvJankyArgs * args =
    g_object_new (T_TEST_TYPE_SRV_JANKY_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gint arg;
    gint return_value;
    TTestSrvJankyResult * result_struct;

    g_object_get (args,
                  "arg", &arg,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (T_TEST_TYPE_SRV_JANKY_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (t_test_srv_handler_janky (T_TEST_SRV_IF (self->handler),
                                  (gint32 *)&return_value,
                                  arg,
                                  error) == TRUE)
    {
      g_object_set (result_struct, "success", (gint)(gint32)return_value, NULL);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "Janky",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Srv.Janky implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "Janky",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
t_test_srv_processor_process_void_method (TTestSrvProcessor *self,
                                          gint32 sequence_id,
                                          ThriftProtocol *input_protocol,
                                          ThriftProtocol *output_protocol,
                                          GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  TTestSrvVoidMethodArgs * args =
    g_object_new (T_TEST_TYPE_SRV_VOID_METHOD_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    TTestSrvVoidMethodResult * result_struct;

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (T_TEST_TYPE_SRV_VOID_METHOD_RESULT, NULL);

    if (t_test_srv_handler_void_method (T_TEST_SRV_IF (self->handler),
                                        error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "voidMethod",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Srv.voidMethod implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "voidMethod",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
t_test_srv_processor_process_primitive_method (TTestSrvProcessor *self,
                                               gint32 sequence_id,
                                               ThriftProtocol *input_protocol,
                                               ThriftProtocol *output_protocol,
                                               GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  TTestSrvPrimitiveMethodArgs * args =
    g_object_new (T_TEST_TYPE_SRV_PRIMITIVE_METHOD_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gint return_value;
    TTestSrvPrimitiveMethodResult * result_struct;

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (T_TEST_TYPE_SRV_PRIMITIVE_METHOD_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (t_test_srv_handler_primitive_method (T_TEST_SRV_IF (self->handler),
                                             (gint32 *)&return_value,
                                             error) == TRUE)
    {
      g_object_set (result_struct, "success", (gint)(gint32)return_value, NULL);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "primitiveMethod",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Srv.primitiveMethod implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "primitiveMethod",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
t_test_srv_processor_process_struct_method (TTestSrvProcessor *self,
                                            gint32 sequence_id,
                                            ThriftProtocol *input_protocol,
                                            ThriftProtocol *output_protocol,
                                            GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  TTestSrvStructMethodArgs * args =
    g_object_new (T_TEST_TYPE_SRV_STRUCT_METHOD_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    TTestCompactProtoTestStruct * return_value;
    TTestSrvStructMethodResult * result_struct;

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (T_TEST_TYPE_SRV_STRUCT_METHOD_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (t_test_srv_handler_struct_method (T_TEST_SRV_IF (self->handler),
                                          &return_value,
                                          error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "structMethod",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Srv.structMethod implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "structMethod",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (return_value != NULL)
      g_object_unref (return_value);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
t_test_srv_processor_process_method_with_default_args (TTestSrvProcessor *self,
                                                       gint32 sequence_id,
                                                       ThriftProtocol *input_protocol,
                                                       ThriftProtocol *output_protocol,
                                                       GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  TTestSrvMethodWithDefaultArgsArgs * args =
    g_object_new (T_TEST_TYPE_SRV_METHOD_WITH_DEFAULT_ARGS_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gint something;
    TTestSrvMethodWithDefaultArgsResult * result_struct;

    g_object_get (args,
                  "something", &something,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (T_TEST_TYPE_SRV_METHOD_WITH_DEFAULT_ARGS_RESULT, NULL);

    if (t_test_srv_handler_method_with_default_args (T_TEST_SRV_IF (self->handler),
                                                     something,
                                                     error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "methodWithDefaultArgs",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("Srv.methodWithDefaultArgs implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "methodWithDefaultArgs",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
t_test_srv_processor_process_oneway_method (TTestSrvProcessor *self,
                                            gint32 sequence_id,
                                            ThriftProtocol *input_protocol,
                                            ThriftProtocol *output_protocol,
                                            GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  TTestSrvOnewayMethodArgs * args =
    g_object_new (T_TEST_TYPE_SRV_ONEWAY_METHOD_ARGS, NULL);

  THRIFT_UNUSED_VAR (sequence_id);
  THRIFT_UNUSED_VAR (output_protocol);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {

    if (t_test_srv_handler_oneway_method (T_TEST_SRV_IF (self->handler),
                                          error) == TRUE)
    {
    }
    else
    {
      if (*error == NULL)
        g_warning ("Srv.onewayMethod implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "onewayMethod",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
t_test_srv_processor_process_declared_exception_method (TTestSrvProcessor *self,
                                                        gint32 sequence_id,
                                                        ThriftProtocol *input_protocol,
                                                        ThriftProtocol *output_protocol,
                                                        GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  TTestSrvDeclaredExceptionMethodArgs * args =
    g_object_new (T_TEST_TYPE_SRV_DECLARED_EXCEPTION_METHOD_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gboolean shouldThrow;
    TTestExceptionWithAMap * xwamap = NULL;
    gboolean return_value;
    TTestSrvDeclaredExceptionMethodResult * result_struct;

    g_object_get (args,
                  "shouldThrow", &shouldThrow,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (T_TEST_TYPE_SRV_DECLARED_EXCEPTION_METHOD_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (t_test_srv_handler_declared_exception_method (T_TEST_SRV_IF (self->handler),
                                                      &return_value,
                                                      shouldThrow,
                                                      &xwamap,
                                                      error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "declaredExceptionMethod",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (xwamap != NULL)
      {
        g_object_set (result_struct,
                      "xwamap", xwamap,
                      NULL);

        g_object_unref (xwamap);
        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "declaredExceptionMethod",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("Srv.declaredExceptionMethod implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "declaredExceptionMethod",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
t_test_srv_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                    ThriftProtocol *input_protocol,
                                    ThriftProtocol *output_protocol,
                                    gchar *method_name,
                                    gint32 sequence_id,
                                    GError **error)
{
  t_test_srv_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  TTestSrvProcessor *self = T_TEST_SRV_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (T_TEST_SRV_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
t_test_srv_processor_set_property (GObject *object,
                                   guint property_id,
                                   const GValue *value,
                                   GParamSpec *pspec)
{
  TTestSrvProcessor *self = T_TEST_SRV_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_T_TEST_SRV_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
t_test_srv_processor_get_property (GObject *object,
                                   guint property_id,
                                   GValue *value,
                                   GParamSpec *pspec)
{
  TTestSrvProcessor *self = T_TEST_SRV_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_T_TEST_SRV_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
t_test_srv_processor_dispose (GObject *gobject)
{
  TTestSrvProcessor *self = T_TEST_SRV_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (t_test_srv_processor_parent_class)->dispose (gobject);
}

static void
t_test_srv_processor_finalize (GObject *gobject)
{
  TTestSrvProcessor *self = T_TEST_SRV_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (t_test_srv_processor_parent_class)->finalize (gobject);
}

static void
t_test_srv_processor_init (TTestSrvProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 7; index += 1)
    g_hash_table_insert (self->process_map,
                         t_test_srv_processor_process_function_defs[index].name,
                         &t_test_srv_processor_process_function_defs[index]);
}

static void
t_test_srv_processor_class_init (TTestSrvProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = t_test_srv_processor_dispose;
  gobject_class->finalize = t_test_srv_processor_finalize;
  gobject_class->set_property = t_test_srv_processor_set_property;
  gobject_class->get_property = t_test_srv_processor_get_property;

  dispatch_processor_class->dispatch_call = t_test_srv_processor_dispatch_call;
  cls->dispatch_call = t_test_srv_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    T_TEST_TYPE_SRV_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_T_TEST_SRV_PROCESSOR_HANDLER,
                                   param_spec);
}
