; SPDX-License-Identifier: EPL-2.0 AND Apache-2.0
; SPDX-FileCopyrightText: © CouchDB Developers <dev@couchdb.apache.org>

; CouchDB Configuration Settings

; Adopted from https://github.com/apache/couchdb-docker/blob/58910ed097489dc588b2a87592406f8faa1bdadf/3.3.3/10-docker-default.ini

[chttpd]
bind_address = any
