#!/bin/bash

# Usage: create.sh [PROJECT_ROOT] [WARS_OUTPUT_DIR] [CONTEXT_DESCRIPTOR_DIR] [RUNTIME_WARS_DIR]
#
# Emits a download.sh script on stdout that:
#   * downloads each war from the GitLab Maven repo into WARS_OUTPUT_DIR
#     (preserving the upstream <artifactId>-<version>.war filename),
#   * writes a Tomcat per-context descriptor for each downloaded war under
#     CONTEXT_DESCRIPTOR_DIR as <deploy.name>.xml, pointing at the war path
#     it will have at runtime (RUNTIME_WARS_DIR/<artifactId>-<version>.war).
#
# This decouples Tomcat's context paths (/resource, /authorization, ...) from
# the upstream Maven war filenames, so the URL space is stable across version
# bumps and -rc tags.

if [ -z "$1" ]; then
  PROJECT_ROOT="$(pwd)/../../"
else
  PROJECT_ROOT="$1"
fi
if [ -z "$2" ]; then
  OUTPUT_DIRECTORY="$(pwd)/wars"
else
  OUTPUT_DIRECTORY="$2"
fi
if [ -z "$3" ]; then
  CONTEXT_DIRECTORY="$(pwd)/context-descriptors"
else
  CONTEXT_DIRECTORY="$3"
fi
if [ -z "$4" ]; then
  # Path the war files will live at when Tomcat reads the descriptors.
  # Defaults to OUTPUT_DIRECTORY if the build-time and runtime layouts match.
  RUNTIME_WARS_DIR="$OUTPUT_DIRECTORY"
else
  RUNTIME_WARS_DIR="$4"
fi

cat <<EOF
#!/bin/bash

# Configuration
GITLAB_REPO="https://code.siemens.com/api/v4/projects/708/packages/maven"
M2_REPO_PATH="\$HOME/.m2/repository"
EOF
printf 'DESTINATION_FOLDER="%s"\n' "$OUTPUT_DIRECTORY"
printf 'CONTEXT_FOLDER="%s"\n' "$CONTEXT_DIRECTORY"
printf 'RUNTIME_WARS_DIR="%s"\n' "$RUNTIME_WARS_DIR"
cat <<EOF

# Create destination folders if they don't exist
mkdir -p "\$DESTINATION_FOLDER" "\$CONTEXT_FOLDER"

# Download a war from the GitLab Maven repo into \$DESTINATION_FOLDER under its
# upstream filename (<artifactId>-<version>.war) and write a Tomcat per-context
# descriptor file \$CONTEXT_FOLDER/<context_path>.xml that mounts it at the
# given context path (e.g. resource, authorization).
download_and_generate_context() {
    local artifact="\$1"
    local context_path="\$2"

    echo "Downloading artifact: \$artifact"

    mvn --no-transfer-progress dependency:get \\
        -Dartifact="\$artifact" \\
        -Dtransitive=false \\
        -DremoteRepositories=gitlab-maven::::\$GITLAB_REPO

    if [ \$? -ne 0 ]; then
        echo "Failed to download artifact: \$artifact"
        return 1
    fi

    local groupId=\$(echo "\$artifact" | cut -d':' -f1)
    local artifactId=\$(echo "\$artifact" | cut -d':' -f2)
    local version=\$(echo "\$artifact" | cut -d':' -f3)
    local packaging=\$(echo "\$artifact" | cut -d':' -f4)

    local group_path=\$(echo "\$groupId" | tr '.' '/')
    local upstream_filename="\$artifactId-\$version.\$packaging"
    local artifact_path="\$M2_REPO_PATH/\$group_path/\$artifactId/\$version/\$upstream_filename"

    if [ ! -f "\$artifact_path" ]; then
        echo "Downloaded artifact not found at expected location: \$artifact_path"
        return 1
    fi

    if [ -z "\$context_path" ]; then
        echo "Refusing to deploy \$upstream_filename without a context path"
        return 1
    fi

    # Copy war to the wars/ output dir under its upstream filename.
    local target_war="\$DESTINATION_FOLDER/\$upstream_filename"
    echo "Copying \$artifact_path -> \$target_war"
    cp "\$artifact_path" "\$target_war" || {
        echo "Failed to copy war for \$artifact"
        return 1
    }

    # Write the matching Tomcat per-context descriptor. The filename (sans .xml)
    # becomes the URL context path. docBase points at where the war will live
    # at runtime, which may differ from the build-time copy location.
    local descriptor="\$CONTEXT_FOLDER/\$context_path.xml"
    cat > "\$descriptor" <<XMLEOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by sw360portal/utils/internal/create.sh -->
<Context docBase="\$RUNTIME_WARS_DIR/\$upstream_filename" reloadable="false" />
XMLEOF

    echo "Wrote context descriptor \$descriptor (path=/\$context_path -> \$RUNTIME_WARS_DIR/\$upstream_filename)"
}

EOF

# For each war pom, resolve the GAV + canonical context path (<deploy.name>)
# and emit a download_and_generate_context call. War modules that do not
# declare a <deploy.name> are skipped with a warning (they have no stable
# public URL anyway).
find $PROJECT_ROOT/backend $PROJECT_ROOT/rest -name "pom.xml" -exec bash -c '
    if grep -q "<packaging>war</packaging>" {}; then
        response=$(echo "\${project.groupId}:\${project.artifactId}:\${project.version}:war \${deploy.name}" | mvn -N -q -DforceStdout help:evaluate -f {} -Dstyle.color=never 2>/dev/null | sed -r "s/\x1B\[[0-9;]*[mK]//g")
        artifact=$(echo $response | awk -F " " "{print \$1}")
        context_path=$(echo $response | awk -F " " "{print \$2}")
        if [ -z "$context_path" ] || [ "$context_path" = "null object or invalid expression" ]; then
            echo "# WARN: {} declares <packaging>war</packaging> but no <deploy.name>; skipping" 1>&2
            exit 0
        fi
        echo "download_and_generate_context \"$artifact\" \"$context_path\""
    fi
' \;
