/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ChildService.h"
#include "thrift/async/TAsyncChannel.h"
#include "ChildService.tcc"

namespace apache { namespace thrift { namespace test {


ChildService_setValue_args::~ChildService_setValue_args() noexcept {
}


ChildService_setValue_pargs::~ChildService_setValue_pargs() noexcept {
}


ChildService_setValue_result::~ChildService_setValue_result() noexcept {
}


ChildService_setValue_presult::~ChildService_setValue_presult() noexcept {
}


ChildService_getValue_args::~ChildService_getValue_args() noexcept {
}


ChildService_getValue_pargs::~ChildService_getValue_pargs() noexcept {
}


ChildService_getValue_result::~ChildService_getValue_result() noexcept {
}


ChildService_getValue_presult::~ChildService_getValue_presult() noexcept {
}

}}} // namespace

