// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "deprecate_everything.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class deprecate_everythingHandler : virtual public deprecate_everythingIf {
 public:
  deprecate_everythingHandler() {
    // Your initialization goes here
  }

  void Foo() {
    // Your implementation goes here
    printf("Foo\n");
  }

  void Bar() {
    // Your implementation goes here
    printf("Bar\n");
  }

  void Baz() {
    // Your implementation goes here
    printf("Baz\n");
  }

  void Deprecated() {
    // Your implementation goes here
    printf("Deprecated\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<deprecate_everythingHandler> handler(new deprecate_everythingHandler());
  ::std::shared_ptr<TProcessor> processor(new deprecate_everythingProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

