/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftTest_constants.h"

namespace thrift { namespace test {

const ThriftTestConstants g_ThriftTest_constants;

ThriftTestConstants::ThriftTestConstants() {
  myNumberz = static_cast<Numberz::type>(1);

}

}} // namespace

