# -----------------------------------------------------------------------------
# Copyright Helio Chissini de Castro 2022-2025
# Copyright Cariad SE 2024
# Part of the SW360 Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# -----------------------------------------------------------------------------

name: SW360 Container

on:
  schedule:
    - cron: '0 0 * * *' # Midnight
  workflow_dispatch:
  pull_request:
    paths:
      - 'Dockerfile'
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

permissions:
  contents: read

jobs:
  sw360_version:
    name: SW360 Version
    runs-on: ubuntu-24.04
    outputs:
      sw360_version: ${{ steps.pom_version.outputs.SW360_VERSION }}
      timestamp: ${{ steps.pom_version.outputs.TIMESTAMP }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout main repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '21'
          cache: 'maven'
          distribution: 'temurin'

      - name: Get revision from pom.xml
        id: pom_version
        run: |
          echo "SW360_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
          echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"

  sw360_image:
    name: SW360 Runtime image
    needs: [sw360_version]
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    env:
      SW360_VERSION: ${{ needs.sw360_version.outputs.sw360_version }}
      TIMESTAMP: ${{ needs.sw360_version.outputs.timestamp }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout main repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Extract components metadata (tags, labels) runtime image
        id: meta_sw360
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern=nightly
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=sha,enable=true,prefix=sha-,format=short
            type=ref,event=tag
            type=raw,value=main,enable={{is_default_branch}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
          labels: |
            org.opencontainers.image.licenses=EPL-2.0
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Extract components metadata (tags, labels) KeyCloak image
        id: meta_keycloak
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/keycloak
          tags: |
            type=schedule,pattern=nightly
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=ref,event=tag
            type=raw,value=main,enable={{is_default_branch}}
            type=raw,value=26.5.5,enable=true
          labels: |
            org.opencontainers.image.licenses=EPL-2.0
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: SW360 image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          target: sw360
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta_sw360.outputs.tags }}
          labels: ${{ steps.meta_sw360.outputs.labels }}
          provenance: mode=max
          sbom: true
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: KeyCloak image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          target: keycloak
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta_keycloak.outputs.tags }}
          labels: ${{ steps.meta_keycloak.outputs.labels }}
          provenance: mode=max
          sbom: true
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
