# -----------------------------------------------------------------------------
# Copyright Helio Chissini de Castro 2022-2025
# Copyright Cariad SE 2024
# Part of the SW360 Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# -----------------------------------------------------------------------------

name: SW360 Thrift Resource Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'third-party/thrift/Dockerfile'

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  THRIFT_VERSION: '0.20.0' # Will be override but post step. Kept it here for minimal version

jobs:
  thrift_image:
    name: Thrift Container
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout main repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Login to GitHub container registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker build
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Get assigned Thrift version
        shell: bash
        run: |
          THRIFT_VERSION="$(cat third-party/thrift/version)"
          echo "THRIFT_VERSION=$THRIFT_VERSION" >> $GITHUB_ENV
          echo "Thrift is set to version $THRIFT_VERSION"

      - name: Extract components metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/thrift
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern=snapshot
            type=semver,pattern={{version}}
            type=raw,value=${{ env.THRIFT_VERSION }}-noble
            type=raw,value=latest
            type=ref,event=tag
          labels: |
            sw360,thrift
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          load: false
          file: third-party/thrift/Dockerfile
          build-args: |
            THRIFT_VERSION=${{ env.THRIFT_VERSION }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
